name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy mail-report-app
        run: |
          set -e

          echo "=== Start Deploy ==="

          cd /home/it/mail-report-app

          echo "=== Current Branch ==="
          git branch

          echo "=== Fetch Latest Code ==="
          git fetch origin

          echo "=== Update To Latest Version ==="
          git reset --hard origin/master

          echo "=== Grant execute permissions to the file ==="
          chmod +x run-job-sal_shpt_cus_dis.sh
          chmod +x run-job-late_pay_req_pur.sh
          chmod +x run-job-carter_miss_po1_45_days.sh
          
          echo "=== Install Dependencies ==="
          /home/it/.nvm/versions/node/v22.18.0/bin/npm ci

          echo "=== Deploy Completed ==="
